#INCLUDE<P16F877A.INC>

__CONFIG _CP_OFF & _CPD_OFF & _DEBUG_OFF & _LVP_OFF & _WRT_OFF
& _BODEN_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC

#DEFINE BANK1 BSF STATUS,RP0
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BT_HOR PORTB,7
#DEFINE BT_ANTIHOR PORTB,6
CBLOCK 0X20
T1
T2
T3
FILTRO1
FILTRO2
ENDC
FILTRO1_VALUE EQU .180
FILTRO2_VALUE EQU .20
ORG 0X0000
GOTO CONFIGURA
ORG 0X0004
GOTO CONFIGURA
;********************************************
DELAY
MOVLW .255
MOVWF T1
MOVLW .255
MOVWF T2
MOVLW .8
MOVWF T3
DELAYAUX
DECFSZ T1
GOTO DELAYAUX
DECFSZ T2
GOTO DELAYAUX
DECFSZ T3
GOTO DELAYAUX
RETURN
;********************************************
CONFIGURA
CLRF PORTA
CLRF PORTB
CLRF PORTC
CLRF PORTD
CLRF PORTE
BANK1
MOVLW B'00000000'
MOVWF TRISA
MOVLW B'11110000'
MOVWF TRISB
MOVLW B'00000000'
MOVWF TRISC
MOVLW B'00000000'
MOVWF TRISD
MOVLW B'00000000'
MOVWF TRISE
MOVLW B'10000100'
MOVWF OPTION_REG
MOVLW B'00000111'
MOVWF ADCON1
BANK0
MOVLW B'00000000'
MOVWF INTCON
HORARIO
BTFSS BT_ANTIHOR
GOTO FILTRO_ANTIHOR
BSF PORTC,7
CALL DELAY
BCF PORTC,7
BSF PORTC,6
CALL DELAY
BCF PORTC,6
BSF PORTC,5
CALL DELAY
BCF PORTC,5
BSF PORTC,4
CALL DELAY
BCF PORTC,4
MOVLW FILTRO1_VALUE
MOVWF FILTRO1
MOVLW FILTRO2_VALUE
MOVWF FILTRO2
GOTO HORARIO
FILTRO_ANTIHOR
DECFSZ FILTRO1
GOTO HORARIO
MOVLW FILTRO1_VALUE
MOVWF FILTRO1
DECFSZ FILTRO2
GOTO HORARIO
MOVLW FILTRO2_VALUE
MOVWF FILTRO2
GOTO ANTI_HORARIO
ANTI_HORARIO
BTFSS BT_HOR
GOTO FILTRO_HOR
BSF PORTC,4
CALL DELAY
BCF PORTC,4
BSF PORTC,5
CALL DELAY
BCF PORTC,5
BSF PORTC,6
CALL DELAY
BCF PORTC,6
BSF PORTC,7
CALL DELAY
BCF PORTC,7
MOVLW FILTRO1_VALUE
MOVWF FILTRO1
MOVLW FILTRO2_VALUE
MOVWF FILTRO2
GOTO ANTI_HORARIO
FILTRO_HOR
DECFSZ FILTRO1
GOTO ANTI_HORARIO
MOVLW FILTRO1_VALUE
MOVWF FILTRO1
DECFSZ FILTRO2
GOTO ANTI_HORARIO
MOVLW FILTRO2_VALUE
MOVWF FILTRO2
GOTO HORARIO
END